"""add data model metadata tables

Revision ID: 984046f6df43
Revises: 4d59c9391c94
Create Date: 2026-07-29 09:23:12.723566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984046f6df43'
down_revision: Union[str, Sequence[str], None] = '4d59c9391c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('json_schema', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_models_table_name'), 'data_models', ['table_name'], unique=False)
    op.create_index(op.f('ix_data_models_tenant_id'), 'data_models', ['tenant_id'], unique=False)
    op.create_table('data_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('db_column_type', sa.String(length=50), nullable=False),
    sa.Column('db_column_def', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['data_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_fields_model_id'), 'data_fields', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_fields_model_id'), table_name='data_fields')
    op.drop_table('data_fields')
    op.drop_index(op.f('ix_data_models_tenant_id'), table_name='data_models')
    op.drop_index(op.f('ix_data_models_table_name'), table_name='data_models')
    op.drop_table('data_models')
    # ### end Alembic commands ###
