"""add llm_providers table

Revision ID: 9a96bf1fa0b6
Revises: 984046f6df43
Create Date: 2026-07-29 19:08:00.466784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a96bf1fa0b6'
down_revision: Union[str, Sequence[str], None] = '984046f6df43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_providers', 'provider_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='openai | claude | wenxin | qianwen | custom',
               existing_nullable=False,
               existing_server_default=sa.text("'openai'"))
    op.alter_column('llm_providers', 'models',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='JSON 数组，如 ["gpt-4", "gpt-3.5-turbo"]',
               existing_nullable=False)
    op.drop_index(op.f('idx_tenant_id'), table_name='llm_providers')
    op.create_index(op.f('ix_llm_providers_tenant_id'), 'llm_providers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_providers_tenant_id'), table_name='llm_providers')
    op.create_index(op.f('idx_tenant_id'), 'llm_providers', ['tenant_id'], unique=False)
    op.alter_column('llm_providers', 'models',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='JSON 数组，如 ["gpt-4", "gpt-3.5-turbo"]',
               existing_nullable=False)
    op.alter_column('llm_providers', 'provider_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='openai | claude | wenxin | qianwen | custom',
               existing_nullable=False,
               existing_server_default=sa.text("'openai'"))
    # ### end Alembic commands ###
